#!/usr/bin/env node
/* build_lists.js — build the shipped `lists.js` sidecar: curation as DATA, not code.
 *
 * WHY (PR-K): the per-site "specials" (Big Five, penguins, endemics) used to be a hardcoded
 * object in app.js, matched to the corpus by COMMON-NAME STRING at boot. That meant curation
 * could not be edited, exported, or shared — and a name drift silently dropped a species.
 *
 * Now they are lists: named, scoped, portable sets of species. This resolves each curated name
 * to a corpus KEY at BUILD time (through the union name index, so synonyms and alternate common
 * names resolve too) and reports anything that fails to match, instead of silently dropping it.
 *
 *   node build_lists.js        # → ../../lists.js
 *
 * The names below are the source of truth (from Shannon's trip digest). Edit here, rebuild.
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '../..');
global.window = global;
require(path.join(ROOT, 'data.js'));
require(path.join(ROOT, 'names.js'));
const UNIC = window.UNIC, NAMES = window.NAMES || {};

var SPECIALS={
  kirstenbosch:["Cape Sugarbird","Orange-breasted Sunbird","Cape Spurfowl","Forest Canary","Cape Batis","African Olive-Pigeon","African Goshawk","Spotted Eagle-Owl","Cape Grysbok","Rock Hyrax"],
  tablemtn:["Cape Sugarbird","Orange-breasted Sunbird","Cape Rock-Thrush","Rock Hyrax","Cape Spurfowl"],
  capepoint:["African Oystercatcher","Kelp Gull","Hartlaub's Gull","Cape Cormorant","Common Ostrich","Cape Sugarbird","Chacma Baboon","Cape Mountain Zebra","Bontebok","Eland"],
  boulders:["African Penguin","Crowned Cormorant","Cape Cormorant","African Oystercatcher","Swift Tern","Rock Hyrax"],
  houtbay:["Cape Fur Seal","Cape Cormorant","Bank Cormorant","Kelp Gull","Hartlaub's Gull","African Oystercatcher"],
  moholoholo:["Cape Vulture","Verreaux's Eagle","African Fish-Eagle","Jackal Buzzard","Narina Trogon","Knysna Turaco","Purple-crested Turaco","Southern Bald Ibis","Malachite Sunbird"],
  blyde:["Cape Vulture","Common Hippopotamus","Nile Crocodile","Greater Kudu","Blue Wildebeest","Waterbuck"],
  karongwe:["Lion","Leopard","African Bush Elephant","White Rhinoceros","African Buffalo","Cheetah","Southern Giraffe","Plains Zebra","Greater Kudu","Spotted Hyena"],
  kruger_letaba:["Lion","Leopard","African Bush Elephant","White Rhinoceros","African Buffalo","Common Hippopotamus","Southern Giraffe","Plains Zebra","African Fish-Eagle","Bateleur"],
  kruger_mdluli:["Lion","Leopard","African Bush Elephant","White Rhinoceros","African Buffalo","Nyala","Vervet Monkey","Southern Giraffe","Impala"]};
// Cross-site lists (not scoped to one locality).
const CROSS = {
  'big-five': { n: 'Big Five', g: '🦁', c: '#8c5a2b',
    it: ['Lion', 'Leopard', 'African Bush Elephant', 'White Rhinoceros', 'African Buffalo'] },
};

// Site display names + order come from the corpus itself.
const SITES = (window.SMETA && window.SMETA.sites) || window.SITES || [];
const siteName = k => { const s = SITES.find(s => s.key === k); return s ? (s.short || s.name || k) : k; };

// Resolve a curated name → corpus key, through EVERY name we know (union rule): common,
// scientific, resolved species, synonyms, vernaculars. Build-time, so misses are loud.
const idx = {};
const nm = s => (s || '').toLowerCase().replace(/[^a-z ]/g, '').replace(/\s+/g, ' ').trim();
UNIC.forEach(o => {
  [o.c, o.s].forEach(n => { if (n && !idx[nm(n)]) idx[nm(n)] = o.k; });
  const N = NAMES[o.k];
  if (N) {
    const al = (N.sp ? [N.sp] : []).concat(N.s || [], N.v || []);
    al.forEach(n => { if (n && !idx[nm(n)]) idx[nm(n)] = o.k; });
  }
});
const byKey = {}; UNIC.forEach(o => byKey[o.k] = o);
const presentAt = (o, site) => !!(o && o.st && o.st[site]);

const out = {};
let miss = 0, dropped = 0, total = 0;

Object.keys(SPECIALS).forEach(site => {
  const items = [];
  SPECIALS[site].forEach(name => {
    total++;
    const k = idx[nm(name)];
    if (!k) { miss++; console.warn('  ✗ no corpus match: "' + name + '" (' + site + ')'); return; }
    // A curated species that isn't actually recorded at that site would be a lie on the site page.
    if (!presentAt(byKey[k], site)) { dropped++; console.warn('  – not recorded at ' + site + ': ' + name); return; }
    if (items.indexOf(k) < 0) items.push(k);
  });
  out['site-' + site] = { n: siteName(site), g: '◆', c: '#5e7249', site: site, it: items };
});

Object.keys(CROSS).forEach(id => {
  const L = CROSS[id];
  const items = [];
  L.it.forEach(name => {
    total++;
    const k = idx[nm(name)];
    if (!k) { miss++; console.warn('  ✗ no corpus match: "' + name + '" (' + id + ')'); return; }
    if (items.indexOf(k) < 0) items.push(k);
  });
  out[id] = { n: L.n, g: L.g, c: L.c, site: '', it: items };
});

const body = '/* Auto-generated by tools/reconcile/build_lists.js — SHIPPED LISTS (curation as data).\n' +
  ' * window.LISTS = { id: {n:name, g:glyph, c:colour, site:siteKey|"", it:[corpusKey]} }\n' +
  ' * These are DEFAULTS: they are seeded into the user\'s list store on first run, after which\n' +
  ' * they are theirs to edit, extend, delete or share. Nothing here is read-only at runtime.\n' +
  ' * Names resolve to corpus keys at BUILD time through the union name index — see the header.\n' +
  ' */\n' +
  'window.LISTS=' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.join(ROOT, 'lists.js'), body);

const n = Object.keys(out).length;
console.log('\nlists.js: ' + n + ' shipped lists · ' + Object.keys(out).reduce((s, k) => s + out[k].it.length, 0) +
  ' memberships (of ' + total + ' curated names)');
console.log('  unmatched names: ' + miss + ' · dropped (not recorded at that site): ' + dropped);
Object.keys(out).forEach(k => console.log('  ' + (out[k].site ? '@' : ' ') + ' ' + k.padEnd(22) + out[k].it.length));
