#!/usr/bin/env node
/* build_bold.js — fold boldcache/ into the bold.js sidecar the app loads.
 *
 * Sidecar, not a data.js rewrite: same pattern as names.js. Keeps the corpus stable and
 * lets barcodes be re-pulled independently.
 *
 *   window.BOLD = { corpusKey: [n, z, inst?] }
 *     n    = barcode records (BOLD specimens, via GBIF/iBOL — see pull_bold.js)
 *     z    = how many of those are from South Africa
 *     inst = the top holding institution, when there is a real one
 *
 * Only species WITH barcodes are emitted; absence is the default.
 *   node build_bold.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const DIR = __dirname;
const CACHE = path.join(DIR, 'boldcache');

global.window = global;
require(path.join(ROOT, 'data.js'));
require(path.join(ROOT, 'names.js'));
const UNIC = window.UNIC, NAMES = window.NAMES || {};
const sciOf = o => { const n = NAMES[o.k]; return (n && n.sp) || o.s || ''; };

const out = {};
let miss = 0, withInst = 0, withZA = 0;
const tot = { n: 0, z: 0 };

UNIC.forEach(o => {
  const f = path.join(CACHE, o.k + '.json');
  if (!fs.existsSync(f)) { miss++; return; }
  let r; try { r = JSON.parse(fs.readFileSync(f, 'utf8')); } catch (e) { miss++; return; }
  if (!r || !r.n) return;                                   // no barcodes → omit
  const row = [r.n, r.z || 0];
  if (r.inst) { row.push(r.inst); withInst++; }
  if (r.z) withZA++;
  out[o.k] = row;
  tot.n += r.n; tot.z += r.z || 0;
});

const keys = Object.keys(out);
const body = '/* Auto-generated by tools/reconcile/build_bold.js — DNA-barcode coverage.\n' +
  ' * ' + keys.length + ' of ' + UNIC.length + ' species have barcode records.\n' +
  ' * [n, z, inst?] = barcode records · how many are South African · top holding institution.\n' +
  ' * Source: BOLD specimens as published to GBIF by iBOL (dataset 040c5662…). BOLD\'s own v4\n' +
  ' * API is quota-capped at ~300 calls and matches names as exact strings; GBIF matches on the\n' +
  ' * backbone, so it also catches synonyms and subspecies. See tools/reconcile/pull_bold.js.\n' +
  ' */\n' +
  'window.BOLD=' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.join(ROOT, 'bold.js'), body);

console.log('bold.js written: ' + keys.length + '/' + UNIC.length + ' species barcoded (' +
  Math.round(keys.length / UNIC.length * 100) + '%)');
console.log('  barcode records: ' + tot.n.toLocaleString() + ' · from South Africa: ' + tot.z.toLocaleString() +
  ' (' + withZA + ' species)');
console.log('  with a named holding institution: ' + withInst);
console.log('  cache misses (not pulled): ' + miss);
console.log('  size: ' + (body.length / 1024).toFixed(1) + ' KB');
